[package]
name = "safecoin-sdk-macro"
version = "1.6.18"
description = "Safecoin SDK Macro"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-sdk-macro"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "solana_sdk_macro"
proc-macro = true

[dependencies]
bs58 = "0.3.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
