[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-local-cluster"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.6.19"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-local-cluster"

[dependencies]
crossbeam-channel = "0.4"
itertools = "0.9.0"
gag = "0.1.10"
fs_extra = "1.2.0"
log = "0.4.11"
rand = "0.7.0"
rayon = "1.5.0"
safecoin-config-program = { path = "../programs/config", version = "=1.6.19" }
safecoin-core = { path = "../core", version = "=1.6.19" }
safecoin-client = { path = "../client", version = "=1.6.19" }
safecoin-download-utils = { path = "../download-utils", version = "=1.6.19" }
safecoin-faucet = { path = "../faucet", version = "=1.6.19" }
safecoin-exchange-program = { path = "../programs/exchange", version = "=1.6.19" }
safecoin-ledger = { path = "../ledger", version = "=1.6.19" }
safecoin-logger = { path = "../logger", version = "=1.6.19" }
safecoin-runtime = { path = "../runtime", version = "=1.6.19" }
safecoin-sdk = { path = "../sdk", version = "=1.6.19" }
safecoin-stake-program = { path = "../programs/stake", version = "=1.6.19" }
safecoin-vest-program = { path = "../programs/vest", version = "=1.6.19" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.6.19" }
tempfile = "3.1.0"
safecoin-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.6.19" }

[dev-dependencies]
assert_matches = "1.3.0"
serial_test = "0.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
