[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-cli-output"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.6.19"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-cli-output"

[dependencies]
base64 = "0.13.0"
chrono = { version = "0.4.11", features = ["serde"] }
console = "0.11.3"
humantime = "2.0.1"
Inflector = "0.11.4"
indicatif = "0.15.0"
serde = "1.0.122"
serde_derive = "1.0.103"
serde_json = "1.0.56"
safecoin-account-decoder = { path = "../account-decoder", version = ">=1.6.18" }
safecoin-clap-utils = { path = "../clap-utils", version = ">=1.6.18" }
safecoin-client = { path = "../client", version = ">=1.6.18" }
safecoin-sdk = { path = "../sdk", version = ">=1.6.18" }
safecoin-stake-program = { path = "../programs/stake", version = ">=1.6.18" }
safecoin-transaction-status = { path = "../transaction-status", version = ">=1.6.21" }
safecoin-vote-program = { path = "../programs/vote", version = ">=1.6.18" }
safe-memo = { version = ">=3.0.4", features = ["no-entrypoint"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
