[package]
name = "safecoin-version"
version = "1.8.12"
description = "Safecoin Version"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-version"
edition = "2018"

[dependencies]
log = "0.4.11"
serde = "1.0.122"
serde_derive = "1.0.103"
safecoin-frozen-abi = { path = "../frozen-abi", version = "=1.8.12" }
safecoin-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.8.12" }
safecoin-logger = { path = "../logger", version = "=1.8.12" }
safecoin-sdk = { path = "../sdk", version = "=1.8.12" }

[lib]
name = "solana_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.2"
