[package]
name = "solana-rpc"
version = "1.10.32"
description = "Safecoin RPC"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-rpc"
edition = "2021"

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
dashmap = "4.0.2"
itertools = "0.10.3"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0" }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
libc = "0.2.120"
log = "0.4.14"
rayon = "1.5.1"
regex = "1.5.4"
serde = "1.0.136"
serde_derive = "1.0.103"
serde_json = "1.0.79"
soketto = "0.7"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.10.32" }
safecoin-client = { path = "../client", version = "=1.10.32" }
solana-entry = { path = "../entry", version = "=1.10.32" }
safecoin-faucet = { path = "../faucet", version = "=1.10.32" }
safecoin-gossip = { path = "../gossip", version = "=1.10.32" }
safecoin-ledger = { path = "../ledger", version = "=1.10.32" }
safecoin-measure = { path = "../measure", version = "=1.10.32" }
safecoin-metrics = { path = "../metrics", version = "=1.10.32" }
safecoin-perf = { path = "../perf", version = "=1.10.32" }
solana-poh = { path = "../poh", version = "=1.10.32" }
safecoin-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.10.32" }
safecoin-runtime = { path = "../runtime", version = "=1.10.32" }
safecoin-sdk = { path = "../sdk", version = "=1.10.32" }
safecoin-send-transaction-service = { path = "../send-transaction-service", version = "=1.10.32" }
safecoin-storage-bigtable = { path = "../storage-bigtable", version = "=1.10.32" }
safecoin-streamer = { path = "../streamer", version = "=1.10.32" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.10.32" }
safecoin-version = { path = "../version", version = "=1.10.32" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.10.32" }
safe-token = { version = "=3.3.0", path = "../../safecoin-program-library/token/program", features = ["no-entrypoint"] }
safe-token-2022 = { version = "0.2.0", path = "../../safecoin-program-library/token/program-2022", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec", "compat"] }

[dev-dependencies]
serial_test = "0.6.0"
safecoin-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.10.32" }
safecoin-net-utils = { path = "../net-utils", version = "=1.10.32" }
safecoin-stake-program = { path = "../programs/stake", version = "=1.10.32" }
symlink = "0.1.0"

[lib]
crate-type = ["lib"]
name = "solana_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
