[package]
name = "safecoin-noop-program"
version = "1.6.18"
description = "Safecoin Noop program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-noop-program"
edition = "2018"

[dependencies]
log = "0.4.11"
safecoin-logger = { path = "../../logger", version = ">=1.6.18" }
safecoin-sdk = { path = "../../sdk", version = ">=1.6.18" }

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_noop_program"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
