[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-transaction-dos"
version = "1.9.29"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
bincode = "1.3.3"
clap = "2.33.1"
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
solana-cli = { path = "../cli", version = "=1.9.29" }
safecoin-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
safecoin-client = { path = "../client", version = "=1.9.29" }
safecoin-core = { path = "../core", version = "=1.9.29" }
safecoin-faucet = { path = "../faucet", version = "=1.9.29" }
safecoin-gossip = { path = "../gossip", version = "=1.9.29" }
safecoin-logger = { path = "../logger", version = "=1.9.29" }
safecoin-measure = { path = "../measure", version = "=1.9.29" }
safecoin-net-utils = { path = "../net-utils", version = "=1.9.29" }
safecoin-runtime = { path = "../runtime", version = "=1.9.29" }
safecoin-sdk = { path = "../sdk", version = "=1.9.29" }
safecoin-streamer = { path = "../streamer", version = "=1.9.29" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.9.29" }
safecoin-version = { path = "../version", version = "=1.9.29" }

[dev-dependencies]
solana-local-cluster = { path = "../local-cluster", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
