[package]
name = "safecoin-exchange-program"
version = "1.6.18"
description = "Safecoin Exchange program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-exchange-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
log = "0.4.11"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = "1.0.122"
serde_derive = "1.0.103"
safecoin-logger = { path = "../../logger", version = ">=1.6.18" }
safecoin-metrics = { path = "../../metrics", version = ">=1.6.18" }
safecoin-sdk = { path = "../../sdk", version = ">=1.6.18" }
thiserror = "1.0"

[dev-dependencies]
safecoin-runtime = { path = "../../runtime", version = ">=1.6.18" }

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_exchange_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
