[package]
name = "safecoin-transaction-status"
version = "1.14.3"
description = "Safecoin transaction status types"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-transaction-status"
license = "Apache-2.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
base64 = "0.13.0"
bincode = "1.3.3"
borsh = "0.9.1"
bs58 = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.17"
serde = "1.0.138"
serde_derive = "1.0.103"
serde_json = "1.0.81"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.14.3" }
safecoin-measure = { path = "../measure", version = "=1.14.3" }
safecoin-metrics = { path = "../metrics", version = "=1.14.3" }
safecoin-sdk = { path = "../sdk", version = "=1.14.3" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.14.3" }
safe-associated-token-account = { version = "=1.1.1", path = "../../safecoin-program-library/associated-token-account/program", features = ["no-entrypoint"] }
safe-memo = { version = "=3.0.5", features = ["no-entrypoint"] }
safe-token = { version = "=3.5.0", path = "../../safecoin-program-library/token/program", features = ["no-entrypoint"] }
safe-token-2022 = { version = "=0.4", path = "../../safecoin-program-library/token/program-2022", features = ["no-entrypoint"] }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
