[package]
name = "safecoin-failure-program"
version = "1.6.18"
description = "Safecoin failure program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-failure-program"
edition = "2018"

[dependencies]
safecoin-sdk = { path = "../../sdk", version = ">=1.6.18" }

[dev-dependencies]
safecoin-runtime = { path = "../../runtime", version = ">=1.6.18" }

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_failure_program"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
