[package]
name = "safecoin-streamer"
version = "1.6.19"
description = "Safecoin Streamer"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-streamer"
edition = "2018"

[dependencies]
log = "0.4.11"
safecoin-metrics = { path = "../metrics", version = "=1.6.19" }
safecoin-sdk = { path = "../sdk", version = "=1.6.19" }
thiserror = "1.0"
safecoin-measure = { path = "../measure", version = "=1.6.19" }
safecoin-logger = { path = "../logger", version = "=1.6.19" }
libc = "0.2.81"
nix = "0.19.0"
safecoin-perf = { path = "../perf", version = "=1.6.19" }

[dev-dependencies]

[lib]
crate-type = ["lib"]
name = "solana_streamer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
