[package]
name = "safecoin-notifier"
version = "1.6.19"
description = "Safecoin Notifier"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-notifier"
edition = "2018"

[dependencies]
log = "0.4.11"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0"

[lib]
name = "solana_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
