[package]
name = "safecoin-perf"
version = "1.6.18"
description = "Safecoin Performance APIs"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-perf"
edition = "2018"

[dependencies]
rand = "0.7.0"
dlopen = "0.1.8"
bincode = "1.3.1"
rayon = "1.5.0"
serde = "1.0.122"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
log = "0.4.11"
safecoin-sdk = { path = "../sdk", version = ">=1.6.18" }
safecoin-rayon-threadlimit = { path = "../rayon-threadlimit", version = ">=1.6.18" }
safecoin-budget-program = { path = "../programs/budget", version = ">=1.6.18" }
safecoin-logger = { path = "../logger", version = ">=1.6.18" }
safecoin-measure = { path = "../measure", version = ">=1.6.18" }
safecoin-metrics = { path = "../metrics", version = ">=1.6.18" }
curve25519-dalek = { version = "2" }

[lib]
name = "solana_perf"

[dev-dependencies]
matches = "0.1.6"

[[bench]]
name = "sigverify"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
