[package]
name = "safecoin-secp256k1-program"
description = "Safecoin Secp256k1 program"
version = "1.6.19"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-secp256k1-program"
repository = "https://github.com/fair-exchange/safecoin"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
safecoin-sdk = { path = "../../sdk", version = ">=1.6.18" }
libsecp256k1 = "0.5.0"
sha3 = "0.9.1"
digest = "0.9.0"
bincode = "1.3.1"
rand = "0.7.0"
safecoin-logger = { path = "../../logger", version = ">=1.6.18" }

[lib]
crate-type = ["lib"]
name = "solana_secp256k1_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
