[package]
name = "safecoin-ledger"
version = "1.14.3"
description = "Safecoin ledger"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-ledger"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitflags = "1.3.1"
byteorder = "1.4.3"
chrono = { version = "0.4.11", features = ["serde"] }
chrono-humanize = "0.2.1"
crossbeam-channel = "0.5"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
fs_extra = "1.2.0"
futures = "0.3.21"
itertools = "0.10.3"
lazy_static = "1.4.0"
libc = "0.2.126"
log = { version = "0.4.17" }
lru = "0.7.7"
num_cpus = "1.13.1"
num_enum = "0.5.7"
prost = "0.11.0"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.3"
reed-solomon-erasure = { version = "5.0.3", features = ["simd-accel"] }
serde = "1.0.138"
serde_bytes = "0.11.6"
sha2 = "0.10.2"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.14.3" }
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.14.3" }
solana-entry = { path = "../entry", version = "=1.14.3" }
safecoin-frozen-abi = { path = "../frozen-abi", version = "=1.14.3" }
safecoin-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.14.3" }
safecoin-measure = { path = "../measure", version = "=1.14.3" }
safecoin-metrics = { path = "../metrics", version = "=1.14.3" }
safecoin-perf = { path = "../perf", version = "=1.14.3" }
safecoin-program-runtime = { path = "../program-runtime", version = "=1.14.3" }
safecoin-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.14.3" }
safecoin-runtime = { path = "../runtime", version = "=1.14.3" }
safecoin-sdk = { path = "../sdk", version = "=1.14.3" }
safecoin-stake-program = { path = "../programs/stake", version = "=1.14.3" }
safecoin-storage-bigtable = { path = "../storage-bigtable", version = "=1.14.3" }
safecoin-storage-proto = { path = "../storage-proto", version = "=1.14.3" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.14.3" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.14.3" }
safe-token = { version = "=3.5.0", path = "../../safecoin-program-library/token/program", features = ["no-entrypoint"] }
safe-token-2022 = { version = "=0.4", path = "../../safecoin-program-library/token/program-2022", features = ["no-entrypoint"] }
static_assertions = "1.1.0"
tempfile = "3.3.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
trees = "0.4.2"

[dependencies.rocksdb]
# Avoid the vendored bzip2 within rocksdb-sys that can cause linker conflicts
# when also using the bzip2 crate
git = "https://github.com/rust-rocksdb/rust-rocksdb"
branch = "master"
default-features = true
#features = ["lz4","snappy"]

[dev-dependencies]
assert_matches = "1.5.0"
bs58 = "0.4.0"
matches = "0.1.9"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.14.3" }
safecoin-logger = { path = "../logger", version = "=1.14.3" }
test-case = "2.1.0"

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_ledger"

[[bench]]
name = "sigverify_shreds"

[[bench]]
name = "blockstore"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
