[package]
name = "solana-bpf-rust-mem"
version = "1.6.19"
description = "Safecoin BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-bpf-rust-mem"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
safecoin-program = { path = "../../../../sdk/program", version = "=1.6.19" }

[dev-dependencies]
safecoin-program-test = { path = "../../../../program-test", version = "=1.6.19" }
safecoin-sdk = { path = "../../../../sdk", version = "=1.6.19" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
