[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-stake-monitor"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.6.18"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-stake-monitor"

[dependencies]
clap = "2.33.1"
console = "0.11.3"
log = "0.4.11"
serde = "1.0.122"
serde_yaml = "0.8.13"
safecoin-clap-utils = { path = "../clap-utils", version = ">=1.6.18" }
safecoin-cli-config = { path = "../cli-config", version = ">=1.6.18" }
safecoin-client = { path = "../client", version = ">=1.6.18" }
safecoin-logger = { path = "../logger", version = ">=1.6.18" }
safecoin-metrics = { path = "../metrics", version = ">=1.6.18" }
safecoin-sdk = { path = "../sdk", version = ">=1.6.18" }
safecoin-stake-program = { path = "../programs/stake", version = ">=1.6.18" }
safecoin-transaction-status = { path = "../transaction-status", version = ">=1.6.21" }
safecoin-version = { path = "../version", version = ">=1.6.18" }

[dev-dependencies]
serial_test = "0.4.0"
solana-local-cluster = { path = "../local-cluster", version = ">=1.6.18" }
safecoin-core = { path = "../core", version = ">=1.6.18" }
tempfile = "3.1.0"

[[bin]]
name = "safecoin-stake-monitor"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
