[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-bench-streamer"
version = "1.7.17"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
clap = "2.33.1"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.7.17" }
safecoin-streamer = { path = "../streamer", version = "=1.7.17" }
safecoin-logger = { path = "../logger", version = "=1.7.17" }
safecoin-net-utils = { path = "../net-utils", version = "=1.7.17" }
safecoin-version = { path = "../version", version = "=1.7.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
