[package]
name = "solana-cargo-test-bpf"
version = "1.6.18"
description = "Execute all unit and integration tests after building with the Safecoin BPF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.12.0"

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
