[package]
name = "solana-cargo-test-bpf"
version = "1.10.32"
description = "Execute all unit and integration tests after building with the Safecoin BPF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.14.2"
clap = { version = "3.1.5", features = ["cargo"] }

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
