[package]
name = "safecoin-account-decoder"
version = "1.8.12"
description = "Safecoin account decoder"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-account-decoder"
license = "Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
bs58 = "0.3.1"
bv = "0.11.1"
Inflector = "0.11.4"
lazy_static = "1.4.0"
serde = "1.0.122"
serde_derive = "1.0.103"
serde_json = "1.0.56"
safecoin-config-program = { path = "../programs/config", version = "=1.8.12" }
safecoin-sdk = { path = "../sdk", version = "=1.8.12" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.8.12" }
safe-token = { version = "=3.2.2", features = ["no-entrypoint"] }
thiserror = "1.0"
zstd = "0.5.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
