[package]
name = "safecoin-test-validator"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.10.32"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-test-validator"
readme = "../README.md"
repository = "https://github.com/fair-exchange/safecoin"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[lib]
name = "solana_test_validator"

[dependencies]
base64 = "0.13.0"
log = "0.4.14"
serde_derive = "1.0.103"
serde_json = "1.0.79"
safecoin-cli-output = { path = "../cli-output", version = "=1.10.32" }
safecoin-client = { path = "../client", version = "=1.10.32" }
safecoin-core = { path = "../core", version = "=1.10.32" }
safecoin-gossip = { path = "../gossip", version = "=1.10.32" }
safecoin-ledger = { path = "../ledger", version = "=1.10.32" }
safecoin-logger = { path = "../logger", version = "=1.10.32" }
safecoin-net-utils = { path = "../net-utils", version = "=1.10.32" }
safecoin-program-test = { path = "../program-test", version = "=1.10.32" }
solana-rpc = { path = "../rpc", version = "=1.10.32" }
safecoin-runtime = { path = "../runtime", version = "=1.10.32" }
safecoin-sdk = { path = "../sdk", version = "=1.10.32" }
safecoin-streamer = { path = "../streamer", version = "=1.10.32" }
tokio = { version = "~1.14.1", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
