[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-install"
description = "The safecoin cluster software installer"
version = "1.14.3"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-install"

[dependencies]
atty = "0.2.11"
bincode = "1.3.3"
bzip2 = "0.4.3"
chrono = { version = "0.4.11", features = ["serde"] }
clap = { version = "2.33.1" }
console = "0.15.0"
crossbeam-channel = "0.5"
ctrlc = { version = "3.2.2", features = ["termination"] }
dirs-next = "2.0.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
nix = "0.24.2"
reqwest = { version = "0.11.11", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
semver = "1.0.10"
serde = { version = "1.0.138", features = ["derive"] }
serde_yaml = "0.8.26"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.14.3" }
safecoin-client = { path = "../client", version = "=1.14.3" }
safecoin-config-program = { path = "../programs/config", version = "=1.14.3" }
safecoin-logger = { path = "../logger", version = "=1.14.3" }
safecoin-sdk = { path = "../sdk", version = "=1.14.3" }
safecoin-version = { path = "../version", version = "=1.14.3" }
tar = "0.4.38"
tempfile = "3.3.0"
url = "2.2.2"

[target."cfg(windows)".dependencies]
winapi = "0.3.8"
winreg = "0.10"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
