[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-scripts"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.6.18"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
csv = "1.1"
serde = { version = "1.0.122", features = ["derive"] }

[[bin]]
name = "safecoin-csv-to-validator-infos"
path = "src/csv_to_validator_infos.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
