[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "Safecoin Program Test Framework"
edition = "2021"
license = "Apache-2.0"
name = "safecoin-program-test"
repository = "https://github.com/fair-exchange/safecoin"
version = "1.10.32"

[dependencies]
async-trait = "0.1.52"
base64 = "0.13.0"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
log = "0.4.14"
serde = "1.0.136"
safecoin-banks-client = { path = "../banks-client", version = "=1.10.32" }
safecoin-banks-server = { path = "../banks-server", version = "=1.10.32" }
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.10.32" }
safecoin-logger = { path = "../logger", version = "=1.10.32" }
safecoin-program-runtime = { path = "../program-runtime", version = "=1.10.32" }
safecoin-runtime = { path = "../runtime", version = "=1.10.32" }
safecoin-sdk = { path = "../sdk", version = "=1.10.32" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.10.32" }
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
