[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "Safecoin Program Test Framework"
edition = "2018"
license = "Apache-2.0"
name = "safecoin-program-test"
repository = "https://github.com/fair-exchange/safecoin"
version = "1.6.18"

[lib]
name = "solana_program_test"

[dependencies]
async-trait = "0.1.42"
base64 = "0.12.3"
bincode = "1.3.1"
chrono = "0.4.19"
chrono-humanize = "0.1.1"
log = "0.4.11"
mio = "0.7.6"
serde = "1.0.112"
serde_derive = "1.0.103"
safecoin-banks-client = { path = "../banks-client", version = ">=1.6.18" }
safecoin-banks-server = { path = "../banks-server", version = ">=1.6.18" }
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = ">=1.6.18" }
safecoin-logger = { path = "../logger", version = ">=1.6.18" }
safecoin-runtime = { path = "../runtime", version = ">=1.6.18" }
safecoin-sdk = { path = "../sdk", version = ">=1.6.18" }
safecoin-vote-program = { path = "../programs/vote", version = ">=1.6.18" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
assert_matches = "1.3.0"
safecoin-stake-program = { path = "../programs/stake", version = ">=1.6.18" }
