[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "Safecoin Program Test Framework"
edition = "2021"
license = "Apache-2.0"
name = "safecoin-program-test"
repository = "https://github.com/fair-exchange/safecoin"
version = "1.9.29"

[dependencies]
async-trait = "0.1.51"
base64 = "0.12.3"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
log = "0.4.14"
serde = "1.0.130"
safecoin-banks-client = { path = "../banks-client", version = "=1.9.29" }
safecoin-banks-server = { path = "../banks-server", version = "=1.9.29" }
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.9.29" }
safecoin-logger = { path = "../logger", version = "=1.9.29" }
safecoin-program-runtime = { path = "../program-runtime", version = "=1.9.29" }
safecoin-runtime = { path = "../runtime", version = "=1.9.29" }
safecoin-sdk = { path = "../sdk", version = "=1.9.29" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.9.29" }
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }

[dev-dependencies]
assert_matches = "1.5.0"
